{"uuid": "5e8ec5f0-948e-4644-9822-65eff73160d7", "children": ["80a69179-5fbe-4c73-8732-93fd54a94371"], "befores": [{"name": "get_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//qa.way2automation.com/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20qa.way2automation.com.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:183:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:541:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:61:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:329:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:154:20\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:35:25\n\n", "trace": "  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Deepak\\PycharmProjects\\pytest_experiment\\Testcases\\conftest.py\", line 35, in get_browser\n    driver.get(configReader.readConfig(\"basic info\",\"testsiteurl\"))\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 449, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684367633053, "stop": 1684367660049}], "start": 1684367633053, "stop": 1684367660098}